name: learn-github-actions
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
    - name: Cypress run
      uses: cypress-io/github-action@v2
      # env:
      #   # DEBUG: "cypress:*"
      #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build: npm run build
        start: npm run server
        wait-on: "http://localhost:3000"
        # record: true
        spec: cypress/integration/test.spec.js